### ISSUE TITLE
'not exist' filters don't work if used alone

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#1]
When subscribing to Kuzzle by filtering documents with only a 'not exist' condition, then:

* documents containing the filtered field are correctly rejected
* documents that don't contain it are not forwarded to the subscriber

Filter example:
```json
{
  "not":
    {
      "exists":
        {
          "field": "some field name"
        }
    }
}
```

The problem lies in the DSL, where we test each filter on fields. When the document don't contain any filtered field, it is automatically rejected.  
If the filter contains any other condition, then everything work fine.

The fix involves a refactor of the way filters are stored. This is already planned to support collection-wide filters.

**Comment by AnthonySendra** [comment]
Currently, we have something like:

```js
filtersTree = {
   message : { // -> collection name
     subject : { // -> attribute where a filter exists
       termSubjectKuzzle : {
         rooms: [ 'f45de4d8ef4f3ze4ffzer85d4fgkzm41'], // -> room id that match this filter
         fn: function () {} // -> function to execute on collection message, on field subject
      }
    }
  }
}
```

The object filtersTree contains an object for each collection that contains an object for each attribute where a filter is bind.  
We have two problems with this architecture: we can't subscribe on a whole collection (every time a modification is made on an object in this collection) and we have the problem explained by @scottinet. In the example above in `filtersTree` we have something like:

```js
filtersTree = {
   message : { // -> collection name
     myField : { // -> attribute where a filter exists
       notExistsMyField : {
         rooms: [ 'f45de4d8ef4f3ze4ffzer85d4fgkzm41'], // -> room id that match this filter
         fn: function () {} // -> function to execute on collection message, on field myField
      }
    }
  }
}
```

So, when a new document is created, we'll check all attributes of this document and check if there is a filter bind to this attribute. The problem is, if the document has not the field `myField`, then... we'll not check if a filter exists and will not execute the related test...

The solution for fix both problems is to allow to bind a filter on a whole collection and test filter each time an object of this collection is created/updated/deleted. We can have something like:

```js
filtersTree = {
   message : { // -> collection name
     filters: [ -> new array with all filters to test in any cases
       {
          rooms: [ 'feg4t465zf4zg4th8errgthyikhrth4zaa'], // -> room id that match this filter
          fn: function () {} // -> function to execute on collection message
       }
     ],
     fields: { -> object with filters to test on specific attribute
       myField : { // -> attribute where a filter exists
         notExistsMyField : {
           rooms: [ 'f45de4d8ef4f3ze4ffzer85d4fgkzm41'], // -> room id that match this filter
           fn: function () {} // -> function to execute on collection message, on field subject
         }
       }
     }
  }
}
```

And we have to detect when we need to add a filter in `filters` (when a filter 'not exists' is the only filter, when the user whant to filter on the whole collection) and when to add a filter in `fields` (in any other cases).  
And obviously, in order to take care about both new entries, we have to adapt the function testFilters in the DSL
