### ISSUE TITLE
An unhandled promise rejection in a plugin controller produces a dump and restart kuzzle

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#1020]
When promise is rejected without being returned or handled within the plugin, an `unhandledRejection` is produced and provokes a core dump and a kuzzle restart.

Log available if asked

**Comment by Aschen** [comment]
An `unhandledRejection` won't make Kuzzle to dump and restart in a production environment (see [kuzzle.js](https://github.com/kuzzleio/kuzzle/blob/master/lib/api/kuzzle.js#L205).  
I don't know if we can really do something about `unhandledRejection` in plugin..

**Comment by Aschen** [comment]
Otherwise there is a mistake in the `unhandledRejection` event handler parameters, the handler take two parameters `reason` and `promise` (see [event unhandledRejection](https://nodejs.org/api/process.html#process_event_unhandledrejection))
The `reason` parameter can also be `undefined` if the promise is rejected with no reason. Maybe we can update the code : 
```
  process.on('unhandledRejection', (reason, promise) => {

    if (reason !== undefined) {
      console.error(`ERROR: unhandledRejection: ${reason.message}`, reason.stack, promise); // eslint-disable-line no-console
    } else {
      console.error('ERROR: unhandledRejection:', promise); // eslint-disable-line no-console
    }
```
