### ISSUE TITLE
Proprerty request.input.headers is undefined

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle#1067]
I created a pipe on `http:options` that looks in the `request.input.headers` to check if a specific header is there.

Here is my code : 
`
if (request.input.headers['origin']) {
    // Do stuff
}
`

The fact is, when I connect to the backoffice (WebSockets) there is no HTTP headers and the property 'headers' is undefined. Leading to a javascript error 'cannot read property origin of null'

I think the "headers" property should always be there, as an object. It should be empty in the case of using others communication protocols.

I agree that I should check if request.input.headers is present but still, it should always be an object

**Comment by scottinet** [comment]
Changed from "bug" to "enhancement", as having a `null` headers object is what's expected when no headers are available.

**Comment by Aschen** [comment]
As far as I know, there is not `http:*` events fired on a websocket connection..  
Maybe I missed something

**Comment by scottinet** [comment]
You're right, there is no `http:*` event triggered on a websocket connection.
However, that's not the point, which is that the `headers` property of the `RequestInput` object is set to `null` if no headers is defined.  The OP states that this property should be, instead, an empty object.

I think that both values are valid ones when there is no header available. I don't have any strong argument for or against either one of these 2 solutions, except that for the sake of consistency, considering that other values are set to `null` if undefined, then a `null` headers property should be favored.

So, unless there is a compelling argument for an empty object instead of a `null` value, I propose that this issue is closed. 
If, on the contrary, it is decided to implement that issue, then it should be regarded as a breaking change, and should be put in the 2.0 backlog.
