### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by pouledodue** [kuzzleio/kuzzle#1219]
Hi
Any plan for a `sdk-dart` for [Flutter](http://flutter.io) ?

**Comment by Aschen** [comment]
Hi @pouledodue !

There is no plan for a Dart SDK by now. But maybe you could ask nicely to our SDK guy @jenow :)

**Comment by Aschen** [comment]
They would be a workaround, you can use [Native Extensions](https://www.dartlang.org/articles/dart-vm/native-extensions) with Dart.
So you can use the `libkuzzlesdk.so` from the [sdk-cpp(https://github.com/kuzzleio/sdk-cpp)

**Comment by pouledodue** [comment]
according to [this](https://gist.github.com/mraleph/2582b57737711da40262fad71215d62e), native extensions do not work with Flutter and they are working on a FFI to bind to C++

**Comment by Aschen** [comment]
Oh ok, so unfortunately there is no way for us to release a SDK for Flutter by now.
It will involve a lot of resources for us to write and maintain a new SDK from scratch. 

You can still use the HTTP Api in your application. The realtime capabilities of Kuzzle use the websocket protocol, it will be a little more harder to implement but it's still possible.

We are aware that more and more Flutter developer are interested by Kuzzle, stay tuned ;)

**Comment by prijindal** [comment]
I have been working on a small library for dart. It also works with flutter
https://github.com/prijindal/kuzzle_dart

It is really beta, and i won't recommend it in production use

**Comment by Aschen** [comment]
Hi @prijindal !

We're very excited about the idea of a sdk dart for Kuzzle. We do not have the internal resources to create and maintain it entirely. 
But we are ready to work with the community to help design it so that it meets the same quality requirements as our other SDKs.

I see you started from SDK JS 5 to create the sdk dart. This one is depreciated and the new version is almost finished (see the branch [6-beta](https://github.com/kuzzleio/sdk-javascript/tree/6-beta)). It would be more appropriate to start from this new version which is clearer and respects the structure of our API.

Feel free to come on [Gitter](https://gitter.im/kuzzleio/kuzzle) to talk about this
