### ISSUE TITLE
Add an argument to document:replace to change the updater instead of the creator in metadata

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#1772]
## Feature description

When a user wants to remove a field from a document, he needs to use the `document:replace` (or `document:createOrReplace`) action and to pass the entire document minus the field he want to remove.

But when a document is replaced, the `creator` and `createdAt` metadata are changed and not the `updater` and `updatedAt` metadata.

We need a way to remove field from a document and modify the metadata like an `document:update`.

## Possible solution (optional)

An argument could be added to the `replace` and `mReplace` actions to keep the original author and update the `updater` and `updatedAt` metadata.

Name suggestions: `keepAuthor`, ...

**Comment by Aschen** [comment]
> Hi @Aschen ,
> 
> Would using `document.update` and setting field to `null` be a possible solution? I have seen other systems use a `null` value to indicate removing a field.

It's an interesting idea but I'm afraid this could be considered as a breaking change regarding the current behavior who allows to have fields equals to `null`.

**Comment by scottinet** [comment]
Also, "make this field null" and "remove that field" have different meanings.

That said, I'm not fond of the `keepAuthor` option. It looks like a workaround to a flawed design to me, I'm not entirely sure the client should be allowed to meddle with documents metadata

I have a few questions to help me pinpoint the problem: 

1. Is it normal to update the `creator` metadata when a document is getting replaced?
2. What's the use case behind that issue? Is there a problem when the creator field is updated instead of the updator one?
3. For a long time now, I'm thinking that our metadata lack a record of all the changes that happened to a document, and I wonder if this kind of problem does not reflect this. Would it help if, additionally to the _latest_ change recorded, we would keep the last few changes of a document (the depth would need to be configurable)?

**Comment by Aschen** [comment]
1. ES only allow to replace entirely or partially update documents so when a document is replaced it can be considered as a delete + create. Even if we wanted to change this behavior we can't without introducing a breaking change

2. One of our client wanted to use the delete a field in several documents so he use the `mReplace` route but he is actually using the metadata and this action is considered as an update.

3. I'm not sure that having an history of metadata containing the list of creators and updater is a good thing. Even if this will eventually allow to solve this issue, this will increase every documents size

**Comment by scottinet** [comment]
I see. In that case, I believe that [this other issue](https://github.com/kuzzleio/kuzzle/issues/1773) sounds like a more suitable solution than asking clients to alter metadata themselves. WDYT?
