### ISSUE TITLE
Incorrect response from "index:exists" in a cluster environment

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#1940]
## Expected Behavior

When starting nodes in a cluster environment, the following code does throws an error:

```
  private async initDatabase () {
    const mutex = new Mutex('initDatabase');

    await mutex.lock();

    try {
      if (! await this.sdk.index.exists('foobar')) {
        await this.sdk.index.create('foobar');
      }
    }
    finally {
      await mutex.unlock();
    }
  }
```

It's because the `index:exists` action use the node index cache to tell if an index exists or not and I suspect the cluster propagation message to be too slow.

**Comment by Aschen** [comment]
I'm not sure about how to resolve this. An quick win would be to ask the storage layer instead of the index cache.

Do we have another solution, specially with the new cluster @scottinet ?

**Comment by scottinet** [comment]
I'm not sure this happens because the cluster sync is too slow. Rather, it might be because the old cluster plugin is initialized after the plugin throwing that error, meaning that there aren't cluster sync at all.

Could you try to reproduce this bug on the `new-cluster` branch? The cluster sync is started before plugins are loaded, so this shouldn't happen anymore.

**Comment by Aschen** [comment]
No more an issue with the new cluster :+1: 

Still, I'm wondering if it could be a race condition if the index cache synchronization message from the cluster arrive too late

**Comment by scottinet** [comment]
It might happen I guess, albeit very rarely. The time needed for the mutex to be reserved should be enough to ensure that the cluster sync is applied, it's pretty damn quick.
