### ISSUE TITLE
SubscribeToSelf not working with volatile message

### ISSUE THREAD

**Issue by Erilan** [kuzzleio/kuzzle#234]
Hi, 

I subscribe to a room with the option "subscribeToSelf" set to "false". When I create a publish a volatile message, i receive it while I should not. If instead i create a document, it works fine, I'm not notified.

To reproduce : 
   - kuzzle tag "beta"

> var filter = {
  term: {
    field: "toto",
  }
}
var options = {
  scope: 'all',
  subscribeToSelf: false
}
var room = kuzzle
  .dataCollectionFactory('my_collection')
  .subscribe(filter, options, (error, result) => {
    if (error) {
      console.error(error)
    } else {
      console.log('response received -->');
      console.log(result);
    }
  })
console.log(room);

Value of var room : 
`callback: (error, result)
channel : "ea9527765b93ddabcd340927d3674068-1c7beed7521fd0b0a8177f219b786d2e"
collection: KuzzleDataCollection
filters : Object
   term: Object
      field: "toto"
      __proto__: Object
__proto__ : Object
headers :Object
id: "97751149-bea1-4c16-9ef8-e794da3b7782"
kuzzle: module.exports.Kuzzle
lastRenewal: 1460577241339
metadata: Object
notifier: ()
queue: Array[0]
renewalDelay: 500
roomId: "ea9527765b93ddabcd340927d3674068"
scope: "all"
state: "done"
subscribeToSelf: false
subscribing: false
users: "none"
__proto__: Object`

**Comment by AnthonySendra** [comment]
Checked with @Erilan:
He's using Kuzzle with webpack and hot-reload, each time his page was updated with webpack, his application made a new subscription. Result was several subscriptions in the same socket, because the page was never refreshed.

The solution is:

```js
if (subscription) {
  subscription.unsubscribe()
}

subscription = kuzzle.dataCollectionFactory('myCollection').subscribe( [...] )
```

Unsubscribe is always a good idea before made a new one ;)
I close this issue. If you see something similar despite the `unsubscribe`, reopen it with new information.
