### ISSUE TITLE
is this supports push notifications?

### ISSUE THREAD

**Issue by santoshgistto** [kuzzleio/kuzzle#250]

**Comment by scottinet** [comment]
Hi,

Kuzzle's notifications are sent by the server, clients only need to subscribe using filters to automatically receive them.
So, yes, our notifications are push notifications. In fact, that's the only kind of notifications we support at the moment. 

If you refer to mobile devices, our SDKs of course allow to subscribe to Kuzzle notifications, and you'll receive them automatically. But we do not provide with specific mobile functionalities, like Android's wakelock, because we feel that we should let developers decide what to do with these notifications.

Does this answer your question?
