### ISSUE TITLE
Default routing controllers plugin

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle#430]
Hi,

As I discussed with @benoitvidis today, when writing controller plugin, if you make a configuration or typing mistake you're redirected to the read controller when using REST protocol (GET).

**Example** : 

We declare a new route called `GET /foo in our plugin kuzzle-plugin-toto`

This one should be exposed at `GET /api/1.0/_plugin/kuzzle-plugin-toto/foo`

For any reason if you fail while registering your routes (or controllers) and you call the route : 

`GET /api/1.0/_plugin/kuzzle-plugin-toto/fooo` or if you try to reach another route that is not registered in the kernel, then **the read controller take the hand**.

I find this weird and a bit annoying because beginner won't understand why they are redirected to the read controller and this can potentially leads to some weird / unexpected behaviors ?

One suggestion might be to have some kind of "404" route for plugins, in case of bad matching ?

What do you think about that ?

Best regards

**Comment by xbill82** [comment]
Is this still relevant? If this is the current behavior I agree with @ScreamZ

**Comment by ballinette** [comment]
should be checked, but I wonder if this issue is not relevant anymore since the merge of #541

**Comment by scottinet** [comment]
This issue has been resolved months ago: our HTTP router controller is now a lot more stricter, and does not fallback to unrelated routes due to regular expressions anymore.
So, in the example provided by @ScreamZ, an invalid URL will properly a 404 error, as expected.

Moreover, it is not possible to define a HTTP route on a non-existing function anymore either: if that happens, Kuzzle will refuse to start until the incriminated plugin is fixed.
