### ISSUE TITLE
Improve response and notification on document update/create

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#485]
Stop sending the entire document in the update response.
- the `create` method should respond with the new document ID
- the `create` method should report the entire document
- the `update` method should respond with an `ack` / error message
- the `update` nofication should only report the updated attributes of the document

**Comment by benoitvidis** [comment]
Some thoughts about this:

Do we want the client to retrieve the changes applied by the pipe plugins?
If the answer is yes, then we have no other choice than to keep the document in the reponse.

About the updates:
The initial need that led to this issue was coming from developers who wanted to know which fields were modified on the update.

Because of the first requirement, I still believe we need to return the whole document but in case of update, we can also return the update request.
Q: Should we include fields that are included in the update request but are not changed (updated with their previous value)?

**Comment by gandbox** [comment]
@kuzzleio/owners Something else to do ? seems done ? or still in progress ?
https://github.com/kuzzleio/sdk-javascript/pull/147

**Comment by scottinet** [comment]
We should keep this one opened, we need a (quick) conception workshop and to either close this issue, or implement it.

The idea behind this issue is that, currently, update notifications contains the whole updated document.
This is less than ideal for some front-end frameworks, listening to document *changes*, because with no way of knowing what in the document changed, these frameworks have to update the entire document interface representation.
This issue comes from the second koding challenge, and a naive implementation would be to split an update notification into two parts: 
* the whole updated document, so that updated documents entering a subscription scope can be properly described by a front-end client
* what has changed in the document

**Comment by ballinette** [comment]
added to backlog

**Comment by Aschen** [comment]
Too old.
