### ISSUE TITLE
Install node packages on buildtime

### ISSUE THREAD

**Issue by killerwolf** [kuzzleio/kuzzle#51]
Node dependencies should be installed on build time (when building the container) not on runtime (when running the container).

**Comment by j33f** [comment]
Could you explain why it "should" be that way, and which are the benefits?

**Comment by killerwolf** [comment]
- `docker build` is meant to build your project
- `docker run` is meant to run your project
`npm install` is a build step

have a look at the 'official' node ONBUILD Dockerfile 
https://github.com/nodejs/docker-node/blob/04df8682a438b0ced8f530ab562f5197595e0cbb/4.2/onbuild/Dockerfile

the more you put in the building step, the more your container is runnable, testable, repeatable.

**Comment by j33f** [comment]
Well, yes,  but... is it really what we need by now ? As Kuzzle is still in alpha version, we need to test and get feedbacks more than to allow Kuzzle to be "transportable". 
Performing an npm install at the beginning of the run stage ensure that everything is okay.

When Kuzzle will be on the RC track to V1, it will be the right time to ship kuzzle with its dependencies directly into the container, and launch it in production mode instead of dev mode. It's all about time :)

Thank you for your interest on the project, we truly appreciate it :)

**Comment by scottinet** [comment]
Hi,

Actually, you're both right. What j33f says was true until not so long ago, when we built our docker images from scratch using symlinks to our Kuzzle sources, in order to refresh our image dynamically during development process.

But now this is not necessary anymore. Furthermore, we have a project dedicated to building docker images (https://github.com/kuzzleio/kuzzle-containers), so having dependencies resolved at build time instead of runtime is more efficient.

We simply forgot about it, I'll fix that when I have the time.

**Comment by scottinet** [comment]
Hi !

I have updated our docker images. Here is the new behavior:

* the ``kuzzleio/kuzzle`` docker image now includes necessary dependencies. No ``npm install`` is performed when executed, except to get plugins. The image is created from the latest commit in the master branch of the project, and is automatically updated.
* the ``docker-compose.yml`` file at the root of the project create a kuzzle instance using the code included in the ``kuzzleio/kuzzle`` image,  no ``npm install`` is executed at run time. This image is to be used by users wishing to easily get started with Kuzzle.
* all docker compose images in the ``docker-compose`` folder behave like before, overriding the content of the ``kuzzleio/kuzzle`` image with the kuzzle code and dependencies present in the local folder. These images are provided for development purposes, and they expect necessary dependencies to be installed beforehand.
