### ISSUE TITLE
Expire token time doesn't seem to work, always expire after 1h

### ISSUE THREAD

**Issue by jenow** [kuzzleio/kuzzle#622]

**Comment by scottinet** [comment]
Weird: according to functional tests (namely, Websocket scenario starting from line 470), this is explicitly tested with an expiration time set to 1 second.

Can you provide some way to reproduce this bug?

**Comment by jenow** [comment]
Sorry it expire even if we set 4h hours.
`kuzzle.login('local', {username, password}, '4h')`

**Comment by scottinet** [comment]
Ok I'll take a look.

**Comment by scottinet** [comment]
I found an interesting bug in Kuzzle's token manager, but this has nothing to do with the current issue.
I'm still unable to reproduce the problem, I'll check if the problem does not come from the BO.

**Comment by scottinet** [comment]
Ok I am finally able to reproduce it. This is not a token expiration problem, everything's fine on that part.
The problem lies in token caching: we store tokens in redis with a TTL set to 34min (wtf is that value anyway?), and after that time it disappears, making Kuzzle answer with a "Invalid Token" error (and not a "Token expired" one).

I'm gonna fix this problem in an incoming PR.
