### ISSUE TITLE
I don't find pipe to work on data before notify

### ISSUE THREAD

**Issue by neolas** [kuzzleio/kuzzle#790]
Hello,

I need to work on data sent by a subscription. I try to use proxy:broadcast but it's in read-only, and proxy:notify is not triggered.

It's a blocker for my personal project, so for the moment I hack the notify function in notifier.js like this : 
```
      kuzzle.pluginsManager.trigger('proxy:beforeNotify', data.payload)
            .then( payload => { data.payload = payload; kuzzle.entryPoints.proxy.dispatch(eventName, data)})
            .catch(err => { console.log("Error : ",err); }); 
```
With this, I can manipulate content before notify with a classic pipe.

Cheers,

**Comment by ballinette** [comment]
Hi @neolas. need to be discussed with the other team members, but your solution looks good to me.
Feel free to suggest a Pull Request with your patch ;)

**Comment by scottinet** [comment]
I disagree. 

I don't see why the already existing `proxy:notify` event cannot be used for this purpose. To me, the best solution is to allow pipe plugins to use it and interact with the notification data before the message is broadcasted.

I'll propose a pull request with this solution.

**Comment by scottinet** [comment]
After reviewing the current (and old) core notifier code, I propose a refactor. This should be fairly quick to implement.

I propose the following:

- `proxy:notify` and `proxy:broadcast` events are removed
- new `notify` specialized events are added:
  - `notify:message`: notifications about realtime messages
  - `notify:document`: notifications about document changes
  - `notify:channel`: notifications about users joining or leaving channels
  - `notify:token`: notifications about token expirations
- pipe plugins can intercept, modify or block notifications
- code split for better readability:
  - the core `notify` function will be split into `notifyDocument`, `notifyMessage`, `notifyChannel` and `notifyToken`
  - the ubiquitous `NotificationObject` will be split into `NotificationDocument`, `NotificationMessage`, `NotificationChannel` and `NotificationToken` classes

The expected gain of these actions are:

- better performances: replacing the polymorphic `NotificationObject` class will allow V8 to treat notification contents as C++ classes instead of dictionaries. Given the possible amount of notifications to process per second, this change might be noticable.
- better separation of concerns and smaller functions/classes => better maintenability
- if necessary, it should be fairly easier to add more events compared to the current code
- this refactor will bring this module in line with our current way of implementing stuff

**Comment by scottinet** [comment]
For the moment I'll delete these two events, so the only breaking change of this refactor will be included in the RC10 version.

We'll decide later when we'll add these new events and refactor the notifier module.
