### ISSUE TITLE
Implement a Timeout for controllers actions

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle#931]
For the time being, Kuzzle does not implement any timeout on controllers.

This can be a problem, especially when the executed code is coming from third parties, like plugins.
If for some reason a controller action does not resolve nor rejects, its execution will be kept forever.

Worse, this leads to 2 additional side-effects:

1. the concurrent requests count keeps increasing forever
2. the event loop keeps feeding up, potentially leading to a situation where node will eventually spend all its execution time checking this ghosts promises results.

The main problem here is about this last point and how to ensure the event loop is not eventually polluted.

One possible solution could be to sandbox all requests (or at least the ones coming from plugins) but it is difficult to estimate the related performance cost attached.

Other suggestions are very welcome.

**Comment by scottinet** [comment]
I investigated the issue a few weeks ago. Unfortunately, sandboxes are not a solution: they share the same event loop and there is no way to control it. The only thing that is sandboxed is V8's context, so that sandboxed code cannot access to the main heap space.

The only way I see to kill an ongoing task would be to put plugins into child processes. But there are also issues with that solution:

* there is still no way to kill a single task, this would only allow to kill a _plugin_, and I don't know how to properly handle that case: what happens to other requests being processed by the plugin at the moment of the kill for instance?
* child processes have a heavy overhead cost, so it's probably best to make plugins share the same child process(es?). But then, if a plugin needs to be killed, then all other hosted plugins are also killed

I really don't think that there is a solution at the moment, other than instructing plugin developers to test their code. To my experience, plugins can always make their host application crash anyway, there is little to no way around it. I mean, what can we do if a plugin decides to kill its host or to explicitly make the application exit?

The only thing I see that we might be able to experiment is to force an eslint check on plugins, deactivating rules regarding coding styles of course.
